import Link from "next/link";
import { notFound } from "next/navigation";

type Project = { title:string; kind:string; intro:string; problem:string; solution:string; flow:string[]; tools:string[]; orientation:"portrait"|"landscape"; images:string[]; live:string; workflow?:string };
const data: Record<string, Project> = {
  "finance-bot": { title:"Personal Finance Telegram Bot", kind:"Telegram Bot · Automation · Dashboard", intro:"Pencatatan keuangan pribadi yang lebih cepat lewat percakapan singkat di Telegram.", problem:"Mencatat pemasukan dan pengeluaran secara konsisten sering terasa merepotkan ketika harus membuka aplikasi atau spreadsheet secara manual.", solution:"Bot menerima catatan sederhana dari Telegram, merapikan data ke Google Sheets, lalu membuat ringkasan yang mudah dipantau melalui dashboard.", flow:["Kirim catatan pemasukan atau pengeluaran lewat Telegram","Bot membaca format dan mengelompokkan transaksi","Data tersimpan otomatis di Google Sheets","Dashboard menampilkan ringkasan yang relevan"], tools:["Telegram","Google Sheets","Web Dashboard","Automation"], orientation:"portrait", images:["/images/bot-keuangan1.jpg","/images/bot-keuangan2.jpg","/images/bot-keuangan3.jpg"], live:"https://t.me/nefinancebot", workflow:"/images/workflow-finance.svg" },
  "work-report-bot": { title:"Work Activity & Sales Report Bot", kind:"Telegram Bot · Reporting · Dashboard", intro:"Pencatatan aktivitas lapangan dan laporan kerja yang lebih rapi tanpa proses input yang berulang.", problem:"Aktivitas seperti kunjungan nasabah, follow-up, dan closing perlu dicatat dengan konsisten agar mudah dilihat kembali dan dirangkum.", solution:"Bot menjadikan Telegram sebagai pintu masuk pencatatan. Setiap aktivitas ditata ke dalam Google Sheets dan diringkas dalam dashboard web.", flow:["Catat aktivitas langsung dari Telegram","Pilih jenis aktivitas dan detail singkat","Data masuk otomatis ke Google Sheets","Lihat ringkasan aktivitas melalui dashboard"], tools:["Telegram","Google Sheets","Reporting","Dashboard"], orientation:"portrait", images:["/images/bot-report.jpg","/images/bot-report1.jpg","/images/bot-report2.jpg","/images/bot-report3.jpg"], live:"https://t.me/reportbsi_bot", workflow:"/images/workflow-report.svg" },
  kabisat: { title:"KABISAT Alumni Website", kind:"Website · Community", intro:"Ruang digital untuk menyatukan informasi, cerita, dan kegiatan alumni KABISAT Angkatan Tujuh.", problem:"Informasi komunitas, program, agenda, dan struktur organisasi perlu memiliki satu tempat yang rapi dan mudah diakses.", solution:"Website komunitas yang responsif untuk menampilkan identitas alumni, agenda, program, serta perkembangan aktivitas dalam satu pengalaman yang mudah dipahami.", flow:["Pengunjung membuka halaman komunitas","Informasi program dan agenda disajikan terstruktur","Cerita dan perkembangan kegiatan dapat diperbarui","Komunitas memiliki pusat informasi yang mudah diakses"], tools:["Website","Responsive Design","Community Platform"], orientation:"landscape", images:["/images/web-kbst.jpg"], live:"https://www.kabisat.site/" }
};
export function generateStaticParams() { return Object.keys(data).map((slug) => ({slug})); }
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const p=data[slug]; if(!p) notFound();
  return <main className="detail"><header className="detail-nav"><Link className="brand" href="/">Nabil<span>.</span></Link><Link href="/#portfolio" className="back">← Kembali ke portfolio</Link></header>
    <section className="detail-hero"><p className="eyebrow"><i /> {p.kind}</p><h1>{p.title}</h1><p>{p.intro}</p><a className="detail-live" href={p.live} target="_blank" rel="noreferrer">Buka live project ↗</a></section>
    <section className="detail-body"><div><p className="detail-label">The context</p><h2>Problem</h2><p>{p.problem}</p></div><div><p className="detail-label">The approach</p><h2>Solution</h2><p>{p.solution}</p></div></section>
    <section className="how"><div><p className="detail-label">From input to outcome</p><h2>How It Works</h2></div><ol>{p.flow.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></section>
    {p.workflow && <section className="workflow-section"><p className="detail-label">Workflow overview</p><h2>Alur Sistem</h2><img src={p.workflow} alt={`Diagram alur ${p.title}`} /></section>}
    <section className="tools"><p className="detail-label">Tools / Integration</p><div className="chips">{p.tools.map((x)=><span key={x}>{x}</span>)}</div></section>
    <section className="gallery"><div><p className="detail-label">Project view</p><h2>Screenshot Gallery</h2><p>Geser ke samping untuk melihat screenshot lainnya.</p></div><div className={`gallery-grid gallery-slider ${p.orientation}`} aria-label={`Screenshot gallery ${p.title}`}>{p.images.map((src,i)=><div className="screenshot-placeholder" key={src}><img src={src} alt={`${p.title} screenshot ${i+1}`} /><div><span>Screenshot {i+1}</span><b>{p.orientation === "portrait" ? "9:16" : "16:9"}</b></div></div>)}</div></section>
    <section className="detail-contact"><p>Punya workflow serupa?</p><a href="https://wa.me/6281292231528" target="_blank">Diskusikan project Anda ↗</a></section></main>;
}
