"use client";

import { useRef, useState } from "react";
import { Language, useLanguage } from "../components/language-provider";

const whatsapp = "https://wa.me/6281292231528";
type Localized = { id: string; en: string };
type Project = { slug: string; title: string; category: Localized; description: Localized; chips: string[]; type: "phone" | "browser"; label: Localized; image: string; live: string };

const projects: Project[] = [
  { slug: "finance-bot", title: "Personal Finance Telegram Bot", category: { id: "Telegram Bot · Automation · Dashboard", en: "Telegram Bot · Automation · Dashboard" }, description: { id: "Bot Telegram untuk mencatat pemasukan dan pengeluaran dengan lebih cepat. Data otomatis tersimpan ke Google Sheets dan dapat dipantau melalui dashboard web.", en: "A Telegram bot for recording income and expenses faster. Data is saved to Google Sheets and monitored through a simple web dashboard." }, chips: ["Telegram", "Google Sheets", "Web Dashboard", "Automation"], type: "phone", label: { id: "Catatan pengeluaran", en: "Expense log" }, image: "/images/bot-keuangan1.jpg", live: "https://t.me/nefinancebot" },
  { slug: "work-report-bot", title: "Work Activity & Sales Report Bot", category: { id: "Telegram Bot · Reporting · Dashboard", en: "Telegram Bot · Reporting · Dashboard" }, description: { id: "Bot Telegram untuk mencatat aktivitas kerja seperti kunjungan nasabah, follow-up, dan closing. Data tersimpan otomatis ke Google Sheets.", en: "A Telegram bot for recording visits, follow-ups, and sales activity. Every entry is saved to Google Sheets and summarized in a web dashboard." }, chips: ["Telegram", "Google Sheets", "Reporting", "Dashboard"], type: "phone", label: { id: "Laporan harian", en: "Daily report" }, image: "/images/bot-report.jpg", live: "https://t.me/reportbsi_bot" },
  { slug: "kabisat", title: "KABISAT Alumni Website", category: { id: "Website · Community", en: "Website · Community" }, description: { id: "Website alumni KABISAT Angkatan Tujuh untuk menampilkan informasi komunitas, struktur organisasi, program, agenda, dan kegiatan alumni.", en: "An alumni website for KABISAT 07, presenting community information, organization structure, programs, events, and alumni activities." }, chips: ["Website", "Responsive Design", "Community Platform"], type: "browser", label: { id: "KABISAT 07", en: "KABISAT 07" }, image: "/images/web-kbst.jpg", live: "https://www.kabisat.site/" },
];

const copy = {
  id: {
    home: "Beranda", portfolio: "Portfolio", about: "Tentang", contact: "Kontak", contactMe: "Hubungi Saya", heroEyebrow: "AI · Automation · Web",
    heroTitle: <>Turning Ideas Into <em>Simple</em> Digital Solutions</>, heroLead: "Saya suka mengulik AI dan automation untuk membuat solusi sederhana yang berguna. Saya terbiasa memanfaatkan AI untuk mengubah ide dan masalah sehari-hari menjadi tools yang bisa digunakan.", focus: "Fokus pada problem solving, workflow, automation, dan hasil akhir — bukan sekadar coding.", viewPortfolio: "Lihat Portfolio", selected: "Selected Work", selectedDesc: "Beberapa project yang saya buat untuk menyederhanakan pencatatan, monitoring, dan workflow sehari-hari.", viewProject: "Lihat Project", liveLink: "Buka live link", swipe: "Geser untuk melihat project lainnya", aboutEyebrow: "About me", aboutTitle: <>Curious by nature.<br/><em>Practical by choice.</em></>, aboutText: ["Saya tertarik dengan AI, automation, dan bagaimana teknologi dapat membantu menyelesaikan pekerjaan yang berulang.", "Saya bukan programmer yang tumbuh dari jalur software engineering tradisional. Sebagian besar proses pengembangan saya dilakukan dengan bantuan AI, eksperimen, dan banyak trial-and-error.", "Yang saya fokuskan bukan sekadar menulis kode, tetapi memahami masalah, menyusun workflow, dan membuat solusi yang benar-benar bisa digunakan."], likes: "What I Like Building", processTitle: "How I Work", processDesc: "Sederhana, terarah, dan selalu dimulai dari masalah yang ingin diselesaikan.", steps: [["Understand", "Memahami masalah dan workflow yang ingin disederhanakan."], ["Build", "Membuat prototype dengan bantuan AI dan tools yang sesuai."], ["Test", "Menguji apakah solusi benar-benar bisa digunakan."], ["Improve", "Memperbaiki berdasarkan kebutuhan pengguna."]], talk: "Let's talk", contactTitle: <>Let&apos;s Build Something <em>Useful.</em></>, contactDesc: "Punya pekerjaan berulang, ide sederhana, atau workflow yang ingin dibuat lebih praktis? Mari diskusikan.", chat: "Chat via WhatsApp", footer: "Nabil Falah — Exploring AI, Automation & Digital Solutions."
  },
  en: {
    home: "Home", portfolio: "Portfolio", about: "About", contact: "Contact", contactMe: "Contact Me", heroEyebrow: "AI · Automation · Web",
    heroTitle: <>Turning Ideas Into <em>Simple</em> Digital Solutions</>, heroLead: "I explore AI and automation to create simple, useful solutions. I use AI to turn everyday ideas and problems into tools people can actually use.", focus: "Focused on problem solving, workflows, automation, and outcomes — beyond just writing code.", viewPortfolio: "View Portfolio", selected: "Selected Work", selectedDesc: "A few projects I built to simplify everyday recording, monitoring, and workflows.", viewProject: "View Project", liveLink: "Open live link", swipe: "Swipe to see more projects", aboutEyebrow: "About me", aboutTitle: <>Curious by nature.<br/><em>Practical by choice.</em></>, aboutText: ["I am interested in AI, automation, and how technology can make repetitive work easier.", "I did not grow through a traditional software engineering path. Most of my development process comes from AI assistance, experiments, and plenty of trial and error.", "My focus is not just writing code. It is understanding the problem, shaping the workflow, and making a solution people can actually use."], likes: "What I Like Building", processTitle: "How I Work", processDesc: "Simple, focused, and always started from a problem worth solving.", steps: [["Understand", "Understand the problem and workflow to simplify."], ["Build", "Build a prototype with AI and the right tools."], ["Test", "Test whether the solution actually works."], ["Improve", "Improve it based on real user needs."]], talk: "Let's talk", contactTitle: <>Let&apos;s Build Something <em>Useful.</em></>, contactDesc: "Have repetitive work, a simple idea, or a workflow that could be more practical? Let's talk.", chat: "Chat via WhatsApp", footer: "Nabil Falah — Exploring AI, Automation & Digital Solutions."
  }
} as const;

function LanguageToggle() {
  const { language, setLanguage } = useLanguage();
  return <div className="language-toggle" aria-label="Choose language"><button className={language === "id" ? "active" : ""} onClick={() => setLanguage("id")}>ID</button><span>/</span><button className={language === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button></div>;
}

function ProjectVisual({ type, label, language }: { type: string; label: string; language: Language }) {
  if (type === "phone") return <div className="phone-visual"><div className="phone-top"><span>9:41</span><span>● ● ●</span></div><div className="telegram-head">✈ <b>{label}</b></div><div className="chat-bubble">{language === "id" ? "Catat pengeluaran hari ini" : "Log today's expense"}</div><div className="chat-bubble me">{language === "id" ? "Makan siang 35.000" : "Lunch 35,000"}</div><div className="mini-sheet"><span>Today</span><b>Rp 35.000</b><i /></div><div className="chat-bubble">{language === "id" ? "Tersimpan ke Google Sheets ✓" : "Saved to Google Sheets ✓"}</div></div>;
  return <div className="browser-visual"><div className="browser-bar"><i /><i /><i /><span>kabisat-07.com</span></div><div className="browser-nav"><b>KABISAT</b><span>About</span><span>Agenda</span><span>Stories</span></div><div className="browser-hero"><p>ALUMNI ANGKATAN TUJUH</p><h4>{language === "id" ? "Terhubung, bertumbuh, berdampak." : "Connect, grow, make an impact."}</h4><button>{language === "id" ? "Jelajahi komunitas" : "Explore community"}</button></div><div className="browser-cards"><i /><i /><i /></div></div>;
}

export default function Home() {
  const rail = useRef<HTMLDivElement>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const { language } = useLanguage();
  const t = copy[language];
  const scrollRail = (direction: number) => rail.current?.scrollBy({ left: direction * 360, behavior: "smooth" });
  const closeMenu = () => setMenuOpen(false);

  return <main>
    <header className="nav"><a href="#beranda" className="brand">Nabil<span>.</span></a><nav className={menuOpen ? "open" : ""}><a href="#beranda" onClick={closeMenu}>{t.home}</a><a href="#portfolio" onClick={closeMenu}>{t.portfolio}</a><a href="#tentang" onClick={closeMenu}>{t.about}</a><a href="#kontak" onClick={closeMenu}>{t.contact}</a></nav><div className="nav-actions"><LanguageToggle /><a className="nav-cta" href={whatsapp} target="_blank">{t.contactMe} <b>↗</b></a></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? "×" : "☰"}</button></header>
    <section id="beranda" className="hero section"><div className="hero-copy reveal"><p className="eyebrow"><i /> {t.heroEyebrow}</p><h1>{t.heroTitle}</h1><p className="lead">{t.heroLead}</p><p className="focus">{t.focus}</p><div className="actions"><a className="button primary" href="#portfolio">{t.viewPortfolio} <b>↓</b></a><a className="button secondary" href={whatsapp} target="_blank">{t.contactMe} <b>↗</b></a></div></div><div className="hero-art reveal"><div className="grid-glow"/><div className="dashboard"><div className="dash-bar"><span /><span /><span /></div><div className="dash-layout"><div className="dash-side"><b>N</b><i /><i /><i /></div><div className="dash-main"><p>My workspace <small>Today</small></p><div className="dash-cards"><div><span className="card-icon">✦</span><small>AI Automation</small><b>Workflow ready</b></div><div><span className="card-icon">↗</span><small>Google Sheets</small><b>Connected</b></div></div><div className="dash-flow"><small>Automation flow</small><div><b>Telegram Bot</b><i>→</i><b>Google Sheets</b><i>→</i><b>Dashboard</b></div></div></div></div></div><div className="float-tag tag-one">Telegram Bot <b>↗</b></div><div className="float-tag tag-two">● Live workflow</div></div></section>
    <section id="portfolio" className="portfolio section"><div className="section-heading reveal"><div><p className="eyebrow"><i /> {t.selected}</p><h2>{t.selected}</h2><p>{t.selectedDesc}</p></div><div className="rail-controls"><button onClick={() => scrollRail(-1)} aria-label="Previous project">←</button><button onClick={() => scrollRail(1)} aria-label="Next project">→</button></div></div><div ref={rail} className="project-rail">{projects.map((p) => <article className="project-card" key={p.slug}><div className={`project-preview ${p.type}`}><img className="project-image" src={p.image} alt={`${p.title} preview`} /></div><div className="project-content"><p className="project-category">{p.category[language]}</p><h3>{p.title}</h3><p>{p.description[language]}</p><div className="chips">{p.chips.map((chip) => <span key={chip}>{chip}</span>)}</div><div className="project-links"><a href={`/projects/${p.slug}`} className="text-link">{t.viewProject} <b>→</b></a><a href={p.live} target="_blank" rel="noreferrer" className="live-link">{t.liveLink} ↗</a></div></div></article>)}</div><p className="swipe-hint">{t.swipe} <span>→</span></p></section>
    <section id="tentang" className="about section"><div className="about-number">01</div><div className="about-copy reveal"><p className="eyebrow"><i /> {t.aboutEyebrow}</p><h2>{t.aboutTitle}</h2><div className="about-text">{t.aboutText.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><aside className="likes reveal"><p>{t.likes}</p>{["AI-assisted tools", "Workflow automation", "Telegram bots", "Simple dashboards", "Simple websites"].map((item, index) => <div key={item}><span>0{index + 1}</span>{item}<b>↗</b></div>)}</aside></section>
    <section id="kontak" className="contact section"><div className="contact-main reveal"><p className="eyebrow light"><i /> {t.talk}</p><h2>{t.contactTitle}</h2><p>{t.contactDesc}</p><a className="button light-button" href={whatsapp} target="_blank">{t.chat} <b>↗</b></a></div><div className="contact-list reveal"><a href={whatsapp} target="_blank"><small>WhatsApp</small><b>081292231528</b><span>↗</span></a><a href="mailto:enefjob@gmail.com"><small>Email</small><b>enefjob@gmail.com</b><span>↗</span></a><a href="https://instagram.com/nabilfalh" target="_blank"><small>Instagram</small><b>@nabilfalh</b><span>↗</span></a></div></section>
    <footer><a className="brand" href="#beranda">Nabil<span>.</span></a><p>{t.footer}</p><span>© {new Date().getFullYear()}</span></footer>
  </main>;
}
