"use client";
import Link from "next/link";
import { useRef, useState } from "react";
const whatsapp = "https://wa.me/6281292231528";
const projects = [
  { slug: "finance-bot", title: "Personal Finance Telegram Bot", category: "Telegram Bot · Automation · Dashboard", description: "Bot Telegram untuk mencatat pemasukan dan pengeluaran dengan lebih cepat. Data otomatis tersimpan ke Google Sheets dan dapat dipantau melalui dashboard web sederhana.", chips: ["Telegram", "Google Sheets", "Web Dashboard", "Automation"], type: "phone", label: "Expense log", image: "/images/bot-keuangan1.jpg", live: "https://t.me/nefinancebot" },
  { slug: "work-report-bot", title: "Work Activity & Sales Report Bot", category: "Telegram Bot · Reporting · Dashboard", description: "Bot Telegram untuk mencatat aktivitas kerja seperti kunjungan nasabah, follow-up, dan closing. Data tersimpan otomatis ke Google Sheets dan dirangkum melalui dashboard web.", chips: ["Telegram", "Google Sheets", "Reporting", "Dashboard"], type: "phone", label: "Daily report", image: "/images/bot-report.jpg", live: "https://t.me/reportbsi_bot" },
  { slug: "kabisat", title: "KABISAT Alumni Website", category: "Website · Community", description: "Website alumni KABISAT Angkatan Tujuh untuk menampilkan informasi komunitas, struktur organisasi, program, agenda, dan perkembangan kegiatan alumni.", chips: ["Website", "Responsive Design", "Community Platform"], type: "browser", label: "KABISAT 07", image: "/images/web-kbst.jpg", live: "https://www.kabisat.site/" },
];
function ProjectVisual({ type, label }: { type: string; label: string }) { if (type === "phone") return <div className="phone-visual"><div className="phone-top"><span>9:41</span><span>●●●</span></div><div className="telegram-head">✈ <b>{label}</b></div><div className="chat-bubble">Catat pengeluaran hari ini</div><div className="chat-bubble me">Makan siang 35.000</div><div className="mini-sheet"><span>Today</span><b>Rp 35.000</b><i /></div><div className="chat-bubble">Tersimpan ke Google Sheets ✓</div></div>; return <div className="browser-visual"><div className="browser-bar"><i /><i /><i /><span>kabisat-07.com</span></div><div className="browser-nav"><b>KABISAT</b><span>About</span><span>Agenda</span><span>Stories</span></div><div className="browser-hero"><p>ALUMNI ANGKATAN TUJUH</p><h4>Terhubung, bertumbuh, berdampak.</h4><button>Explore community</button></div><div className="browser-cards"><i /><i /><i /></div></div>; }
export default function Home() { const rail = useRef<HTMLDivElement>(null); const [menuOpen, setMenuOpen] = useState(false); const scrollRail = (d: number) => rail.current?.scrollBy({ left: d * 360, behavior: "smooth" }); return <main>
  <header className="nav"><a href="#beranda" className="brand">Nabil<span>.</span></a><nav className={menuOpen ? "open" : ""}><a href="#beranda" onClick={() => setMenuOpen(false)}>Beranda</a><a href="#portfolio" onClick={() => setMenuOpen(false)}>Portfolio</a><a href="#tentang" onClick={() => setMenuOpen(false)}>Tentang</a><a href="#kontak" onClick={() => setMenuOpen(false)}>Kontak</a></nav><a className="nav-cta" href={whatsapp} target="_blank">Hubungi Saya <b>↗</b></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Buka menu">{menuOpen ? "×" : "☰"}</button></header>
  <section id="beranda" className="hero section"><div className="hero-copy reveal"><p className="eyebrow"><i /> AI · Automation · Web</p><h1>Turning Ideas Into <em>Simple</em> Digital Solutions</h1><p className="lead">Saya suka mengulik AI dan automation untuk membuat solusi sederhana yang berguna. Saya bukan software engineer tradisional, tetapi saya terbiasa memanfaatkan AI untuk mengubah ide dan masalah sehari-hari menjadi tools yang bisa digunakan.</p><p className="focus">Fokus pada problem solving, workflow, automation, dan hasil akhir — bukan sekadar coding.</p><div className="actions"><a className="button primary" href="#portfolio">Lihat Portfolio <b>↓</b></a><a className="button secondary" href={whatsapp} target="_blank">Hubungi Saya <b>↗</b></a></div></div><div className="hero-art reveal"><div className="grid-glow"/><div className="dashboard"><div className="dash-bar"><span /><span /><span /></div><div className="dash-layout"><div className="dash-side"><b>N</b><i /><i /><i /></div><div className="dash-main"><p>My workspace <small>Today</small></p><div className="dash-cards"><div><span className="card-icon">✦</span><small>AI Automation</small><b>Workflow ready</b></div><div><span className="card-icon">↗</span><small>Google Sheets</small><b>Connected</b></div></div><div className="dash-flow"><small>Automation flow</small><div><b>Telegram Bot</b><i>→</i><b>Google Sheets</b><i>→</i><b>Dashboard</b></div></div></div></div></div><div className="float-tag tag-one">Telegram Bot <b>↗</b></div><div className="float-tag tag-two">● Live workflow</div></div></section>
  <section id="portfolio" className="portfolio section"><div className="section-heading reveal"><div><p className="eyebrow"><i /> Selected work</p><h2>Selected Work</h2><p>Beberapa project yang saya buat untuk menyederhanakan pencatatan, monitoring, dan workflow sehari-hari.</p></div><div className="rail-controls"><button onClick={() => scrollRail(-1)} aria-label="Project sebelumnya">←</button><button onClick={() => scrollRail(1)} aria-label="Project berikutnya">→</button></div></div><div ref={rail} className="project-rail">{projects.map((p) => <article className="project-card" key={p.slug}><div className={`project-preview ${p.type}`}>{p.image ? <img className="project-image" src={p.image} alt={`${p.title} preview`} /> : <ProjectVisual type={p.type} label={p.label} />}</div><div className="project-content"><p className="project-category">{p.category}</p><h3>{p.title}</h3><p>{p.description}</p><div className="chips">{p.chips.map((c) => <span key={c}>{c}</span>)}</div><div className="project-links"><a href={`/projects/${p.slug}`} className="text-link">Lihat Project <b>→</b></a><a href={p.live} target="_blank" rel="noreferrer" className="live-link">Buka live link ↗</a></div></div></article>)}</div><p className="swipe-hint">Geser untuk melihat project lainnya <span>→</span></p></section>
  <section id="tentang" className="about section"><div className="about-number">01</div><div className="about-copy reveal"><p className="eyebrow"><i /> About me</p><h2>Curious by nature.<br/><em>Practical by choice.</em></h2><div className="about-text"><p>Saya tertarik dengan AI, automation, dan bagaimana teknologi dapat membantu menyelesaikan pekerjaan yang berulang.</p><p>Saya bukan programmer yang tumbuh dari jalur software engineering tradisional. Sebagian besar proses pengembangan saya dilakukan dengan bantuan AI, eksperimen, dan banyak trial-and-error.</p><p>Yang saya fokuskan bukan sekadar menulis kode, tetapi memahami masalah, menyusun workflow, dan membuat solusi yang benar-benar bisa digunakan.</p></div></div><aside className="likes reveal"><p>What I Like Building</p>{["AI-assisted tools", "Workflow automation", "Telegram bots", "Simple dashboards", "Simple websites"].map((x, i) => <div key={x}><span>0{i + 1}</span>{x}<b>↗</b></div>)}</aside></section>
  <section className="process section"><div className="section-heading reveal"><div><h2>How I Work</h2></div><p>Sederhana, terarah, dan selalu dimulai dari masalah yang ingin diselesaikan.</p></div><div className="steps">{[["01", "Understand", "Memahami masalah dan workflow yang ingin disederhanakan."], ["02", "Build", "Membuat prototype dengan bantuan AI dan tools yang sesuai."], ["03", "Test", "Menguji apakah solusi benar-benar bisa digunakan."], ["04", "Improve", "Memperbaiki berdasarkan kebutuhan pengguna."]].map(([n,t,x]) => <article className="step reveal" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div></section>
  <section id="kontak" className="contact section"><div className="contact-main reveal"><p className="eyebrow light"><i /> Let&apos;s talk</p><h2>Let&apos;s Build Something <em>Useful.</em></h2><p>Punya pekerjaan berulang, ide sederhana, atau workflow yang ingin dibuat lebih praktis? Mari diskusikan.</p><a className="button light-button" href={whatsapp} target="_blank">Chat via WhatsApp <b>↗</b></a></div><div className="contact-list reveal"><a href={whatsapp} target="_blank"><small>WhatsApp</small><b>081292231528</b><span>↗</span></a><a href="mailto:enefjob@gmail.com"><small>Email</small><b>enefjob@gmail.com</b><span>↗</span></a><a href="https://instagram.com/nabilfalh" target="_blank"><small>Instagram</small><b>@nabilfalh</b><span>↗</span></a></div></section>
  <footer><a className="brand" href="#beranda">Nabil<span>.</span></a><p>Nabil Falah — Exploring AI, Automation &amp; Digital Solutions.</p><span>© {new Date().getFullYear()}</span></footer></main>; }
