"use client";

import Link from "next/link";
import { useLanguage } from "./language-provider";

type Localized = { id: string; en: string };
type Project = { title: string; kind: Localized; intro: Localized; problem: Localized; solution: Localized; flow: Localized[]; tools: string[]; orientation: "portrait" | "landscape"; images: string[]; live: string; workflow?: string };

const data: Record<string, Project> = {
  "finance-bot": { title: "Personal Finance Telegram Bot", kind: { id: "Telegram Bot · Automation · Dashboard", en: "Telegram Bot · Automation · Dashboard" }, intro: { id: "Pencatatan keuangan pribadi yang lebih cepat lewat percakapan singkat di Telegram.", en: "Faster personal finance tracking through a short Telegram conversation." }, problem: { id: "Mencatat pemasukan dan pengeluaran secara konsisten sering terasa merepotkan ketika harus membuka aplikasi atau spreadsheet secara manual.", en: "Consistently recording income and expenses feels tedious when it requires opening an app or spreadsheet manually." }, solution: { id: "Bot menerima catatan sederhana dari Telegram, merapikan data ke Google Sheets, lalu membuat ringkasan yang mudah dipantau melalui dashboard.", en: "The bot receives a simple Telegram note, organizes it in Google Sheets, and creates a summary that is easy to monitor through a dashboard." }, flow: [{ id: "Kirim catatan pemasukan atau pengeluaran lewat Telegram", en: "Send an income or expense note through Telegram" }, { id: "Bot membaca format dan mengelompokkan transaksi", en: "The bot reads the format and groups the transaction" }, { id: "Data tersimpan otomatis di Google Sheets", en: "Data is saved automatically in Google Sheets" }, { id: "Dashboard menampilkan ringkasan yang relevan", en: "The dashboard displays a relevant summary" }], tools: ["Telegram", "Google Sheets", "Web Dashboard", "Automation"], orientation: "portrait", images: ["/images/bot-keuangan1.jpg", "/images/bot-keuangan2.jpg", "/images/bot-keuangan3.jpg"], live: "https://t.me/nefinancebot", workflow: "/images/workflow-finance.svg" },
  "work-report-bot": { title: "Work Activity & Sales Report Bot", kind: { id: "Telegram Bot · Reporting · Dashboard", en: "Telegram Bot · Reporting · Dashboard" }, intro: { id: "Pencatatan aktivitas lapangan dan laporan kerja yang lebih rapi tanpa proses input yang berulang.", en: "Cleaner field activity and work reporting without repetitive data entry." }, problem: { id: "Aktivitas seperti kunjungan nasabah, follow-up, dan closing perlu dicatat dengan konsisten agar mudah dilihat kembali dan dirangkum.", en: "Activities such as client visits, follow-ups, and sales need consistent records so they can be reviewed and summarized easily." }, solution: { id: "Bot menjadikan Telegram sebagai pintu masuk pencatatan. Setiap aktivitas ditata ke dalam Google Sheets dan diringkas dalam dashboard web.", en: "The bot turns Telegram into the entry point for reporting. Each activity is organized in Google Sheets and summarized in a web dashboard." }, flow: [{ id: "Catat aktivitas langsung dari Telegram", en: "Record an activity directly from Telegram" }, { id: "Pilih jenis aktivitas dan detail singkat", en: "Choose an activity type and add a short detail" }, { id: "Data masuk otomatis ke Google Sheets", en: "Data is sent automatically to Google Sheets" }, { id: "Lihat ringkasan aktivitas melalui dashboard", en: "View the activity summary in the dashboard" }], tools: ["Telegram", "Google Sheets", "Reporting", "Dashboard"], orientation: "portrait", images: ["/images/bot-report.jpg", "/images/bot-report1.jpg", "/images/bot-report2.jpg", "/images/bot-report3.jpg"], live: "https://t.me/reportbsi_bot", workflow: "/images/workflow-report.svg" },
  kabisat: { title: "KABISAT Alumni Website", kind: { id: "Website · Community", en: "Website · Community" }, intro: { id: "Ruang digital untuk menyatukan informasi, cerita, dan kegiatan alumni KABISAT Angkatan Tujuh.", en: "A digital space bringing together the information, stories, and activities of KABISAT 07 alumni." }, problem: { id: "Informasi komunitas, program, agenda, dan struktur organisasi perlu memiliki satu tempat yang rapi dan mudah diakses.", en: "Community information, programs, events, and organization structure needed one clear and accessible home." }, solution: { id: "Website komunitas yang responsif untuk menampilkan identitas alumni, agenda, program, serta perkembangan aktivitas dalam satu pengalaman yang mudah dipahami.", en: "A responsive community website presenting the alumni identity, events, programs, and activity updates in one clear experience." }, flow: [{ id: "Pengunjung membuka halaman komunitas", en: "Visitors open the community page" }, { id: "Informasi program dan agenda disajikan terstruktur", en: "Program and event information is presented clearly" }, { id: "Cerita dan perkembangan kegiatan dapat diperbarui", en: "Stories and activity updates can be refreshed" }, { id: "Komunitas memiliki pusat informasi yang mudah diakses", en: "The community has an accessible information hub" }], tools: ["Website", "Responsive Design", "Community Platform"], orientation: "landscape", images: ["/images/web-kbst.jpg"], live: "https://www.kabisat.site/" }
};

export default function ProjectDetail({ slug }: { slug: string }) {
  const { language } = useLanguage();
  const p = data[slug];
  if (!p) return null;
  const text = (value: Localized) => value[language];
  const labels = language === "id" ? { back: "Kembali ke portfolio", live: "Buka live project", context: "Konteks", approach: "Pendekatan", problem: "Problem", solution: "Solution", input: "Dari input ke hasil", how: "Cara Kerja", workflow: "Gambaran workflow", system: "Alur Sistem", tools: "Tools / Integrasi", view: "Project view", gallery: "Galeri Screenshot", swipe: "Geser ke samping untuk melihat screenshot lainnya.", similar: "Punya workflow serupa?", discuss: "Diskusikan project Anda" } : { back: "Back to portfolio", live: "Open live project", context: "The context", approach: "The approach", problem: "Problem", solution: "Solution", input: "From input to outcome", how: "How It Works", workflow: "Workflow overview", system: "System Flow", tools: "Tools / Integration", view: "Project view", gallery: "Screenshot Gallery", swipe: "Swipe sideways to see more screenshots.", similar: "Have a similar workflow?", discuss: "Discuss your project" };
  return <main className="detail"><header className="detail-nav"><Link className="brand" href="/">Nabil<span>.</span></Link><Link href="/#portfolio" className="back">← {labels.back}</Link></header>
    <section className="detail-hero"><p className="eyebrow"><i /> {text(p.kind)}</p><h1>{p.title}</h1><p>{text(p.intro)}</p><a className="detail-live" href={p.live} target="_blank" rel="noreferrer">{labels.live} ↗</a></section>
    <section className="detail-body"><div><p className="detail-label">{labels.context}</p><h2>{labels.problem}</h2><p>{text(p.problem)}</p></div><div><p className="detail-label">{labels.approach}</p><h2>{labels.solution}</h2><p>{text(p.solution)}</p></div></section>
    <section className="how"><div><p className="detail-label">{labels.input}</p><h2>{labels.how}</h2></div><ol>{p.flow.map((item, index) => <li key={item.id}><span>0{index + 1}</span>{text(item)}</li>)}</ol></section>
    {p.workflow && <section className="workflow-section"><p className="detail-label">{labels.workflow}</p><h2>{labels.system}</h2><img src={p.workflow} alt={"Workflow diagram for " + p.title} /></section>}
    <section className="tools"><p className="detail-label">{labels.tools}</p><div className="chips">{p.tools.map((tool) => <span key={tool}>{tool}</span>)}</div></section>
    <section className="gallery"><div><p className="detail-label">{labels.view}</p><h2>{labels.gallery}</h2><p>{labels.swipe}</p></div><div className={"gallery-grid gallery-slider " + p.orientation} aria-label={labels.gallery + " " + p.title}>{p.images.map((src, index) => <div className="screenshot-placeholder" key={src}><img src={src} alt={p.title + " screenshot " + (index + 1)} /><div><span>Screenshot {index + 1}</span><b>{p.orientation === "portrait" ? "9:16" : "16:9"}</b></div></div>)}</div></section>
    <section className="detail-contact"><p>{labels.similar}</p><a href="https://wa.me/6281292231528" target="_blank">{labels.discuss} ↗</a></section></main>;
}
